# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fly_gui_edit.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
import sys
from PyQt5.QtCore import QCoreApplication, Qt
from PyQt5.QtGui import QIcon, QColor
from PyQt5.QtWidgets import QApplication, QWidget, QMainWindow, QPushButton, QAction, QMessageBox
from PyQt5.QtWidgets import QCalendarWidget, QFontDialog, QColorDialog, QTextEdit, QFileDialog
from PyQt5.QtWidgets import QCheckBox, QProgressBar, QComboBox, QLabel, QStyleFactory, QLineEdit, QInputDialog


class Ui_window(QMainWindow):
    def __init__(self):
        super().__init__()
    
    def setupUi(self, window):
        window.setObjectName("window")
        window.resize(1074, 614)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        window.setFont(font)
        window.setStatusTip("")
        self.centralwidget = QtWidgets.QWidget(window)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.HXN_GUI_tabs = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.HXN_GUI_tabs.sizePolicy().hasHeightForWidth())
        self.HXN_GUI_tabs.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.HXN_GUI_tabs.setFont(font)
        self.HXN_GUI_tabs.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.HXN_GUI_tabs.setStyleSheet("font: 10pt \"Arial\";")
        self.HXN_GUI_tabs.setTabPosition(QtWidgets.QTabWidget.North)
        self.HXN_GUI_tabs.setDocumentMode(True)
        self.HXN_GUI_tabs.setTabsClosable(False)
        self.HXN_GUI_tabs.setMovable(True)
        self.HXN_GUI_tabs.setTabBarAutoHide(False)
        self.HXN_GUI_tabs.setObjectName("HXN_GUI_tabs")
        self.scan = QtWidgets.QWidget()
        self.scan.setObjectName("scan")
        self.Select_Motor_4 = QtWidgets.QComboBox(self.scan)
        self.Select_Motor_4.setGeometry(QtCore.QRect(130, 90, 81, 22))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Select_Motor_4.sizePolicy().hasHeightForWidth())
        self.Select_Motor_4.setSizePolicy(sizePolicy)
        self.Select_Motor_4.setObjectName("Select_Motor_4")
        self.Select_Motor_4.addItem("")
        self.Select_Motor_4.addItem("")
        self.Select_Motor_4.addItem("")
        self.x_start = QtWidgets.QDoubleSpinBox(self.scan)
        self.x_start.setGeometry(QtCore.QRect(230, 90, 91, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.x_start.sizePolicy().hasHeightForWidth())
        self.x_start.setSizePolicy(sizePolicy)
        self.x_start.setPrefix("")
        self.x_start.setMinimum(-15.0)
        self.x_start.setMaximum(15.0)
        self.x_start.setSingleStep(0.5)
        self.x_start.setProperty("value", -15.0)
        self.x_start.setObjectName("x_start")
        self.y_start = QtWidgets.QDoubleSpinBox(self.scan)
        self.y_start.setGeometry(QtCore.QRect(230, 150, 91, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.y_start.sizePolicy().hasHeightForWidth())
        self.y_start.setSizePolicy(sizePolicy)
        self.y_start.setPrefix("")
        self.y_start.setMinimum(-15.0)
        self.y_start.setMaximum(15.0)
        self.y_start.setSingleStep(0.5)
        self.y_start.setProperty("value", -15.0)
        self.y_start.setObjectName("y_start")
        self.y_end = QtWidgets.QDoubleSpinBox(self.scan)
        self.y_end.setGeometry(QtCore.QRect(340, 150, 91, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.y_end.sizePolicy().hasHeightForWidth())
        self.y_end.setSizePolicy(sizePolicy)
        self.y_end.setSuffix("um")
        self.y_end.setMinimum(-15.0)
        self.y_end.setMaximum(15.0)
        self.y_end.setSingleStep(0.5)
        self.y_end.setProperty("value", 15.0)
        self.y_end.setObjectName("y_end")
        self.Select_Motor_3 = QtWidgets.QComboBox(self.scan)
        self.Select_Motor_3.setGeometry(QtCore.QRect(130, 150, 81, 22))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Select_Motor_3.sizePolicy().hasHeightForWidth())
        self.Select_Motor_3.setSizePolicy(sizePolicy)
        self.Select_Motor_3.setObjectName("Select_Motor_3")
        self.Select_Motor_3.addItem("")
        self.Select_Motor_3.addItem("")
        self.Select_Motor_3.addItem("")
        self.Dets_2 = QtWidgets.QComboBox(self.scan)
        self.Dets_2.setGeometry(QtCore.QRect(31, 120, 71, 22))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Dets_2.sizePolicy().hasHeightForWidth())
        self.Dets_2.setSizePolicy(sizePolicy)
        self.Dets_2.setObjectName("Dets_2")
        self.Dets_2.addItem("")
        self.Dets_2.addItem("")
        self.Dets_2.addItem("")
        self.label_8 = QtWidgets.QLabel(self.scan)
        self.label_8.setGeometry(QtCore.QRect(640, 130, 141, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.tot_time = QtWidgets.QLineEdit(self.scan)
        self.tot_time.setGeometry(QtCore.QRect(630, 150, 154, 22))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tot_time.sizePolicy().hasHeightForWidth())
        self.tot_time.setSizePolicy(sizePolicy)
        self.tot_time.setReadOnly(True)
        self.tot_time.setObjectName("tot_time")
        self.res = QtWidgets.QLineEdit(self.scan)
        self.res.setGeometry(QtCore.QRect(630, 90, 154, 22))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.res.sizePolicy().hasHeightForWidth())
        self.res.setSizePolicy(sizePolicy)
        self.res.setReadOnly(True)
        self.res.setObjectName("res")
        self.strat = QtWidgets.QPushButton(self.scan)
        self.strat.setGeometry(QtCore.QRect(840, 90, 111, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.strat.sizePolicy().hasHeightForWidth())
        self.strat.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.strat.setFont(font)
        self.strat.setStyleSheet("background-color: rgb(170, 255, 127);\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"")
        self.strat.setObjectName("strat")
        self.x_end = QtWidgets.QDoubleSpinBox(self.scan)
        self.x_end.setGeometry(QtCore.QRect(340, 90, 91, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.x_end.sizePolicy().hasHeightForWidth())
        self.x_end.setSizePolicy(sizePolicy)
        self.x_end.setSuffix("um")
        self.x_end.setMinimum(-15.0)
        self.x_end.setMaximum(15.0)
        self.x_end.setSingleStep(0.5)
        self.x_end.setProperty("value", 15.0)
        self.x_end.setObjectName("x_end")
        self.x_step = QtWidgets.QSpinBox(self.scan)
        self.x_step.setGeometry(QtCore.QRect(450, 90, 52, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.x_step.sizePolicy().hasHeightForWidth())
        self.x_step.setSizePolicy(sizePolicy)
        self.x_step.setMaximum(1000)
        self.x_step.setSingleStep(10)
        self.x_step.setProperty("value", 30)
        self.x_step.setObjectName("x_step")
        self.y_step = QtWidgets.QSpinBox(self.scan)
        self.y_step.setGeometry(QtCore.QRect(450, 150, 52, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.y_step.sizePolicy().hasHeightForWidth())
        self.y_step.setSizePolicy(sizePolicy)
        self.y_step.setMaximum(1000)
        self.y_step.setSingleStep(10)
        self.y_step.setProperty("value", 30)
        self.y_step.setObjectName("y_step")
        self.dwell = QtWidgets.QDoubleSpinBox(self.scan)
        self.dwell.setGeometry(QtCore.QRect(530, 120, 81, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dwell.sizePolicy().hasHeightForWidth())
        self.dwell.setSizePolicy(sizePolicy)
        self.dwell.setPrefix("")
        self.dwell.setSuffix("sec")
        self.dwell.setMaximum(0.5)
        self.dwell.setSingleStep(0.01)
        self.dwell.setProperty("value", 0.05)
        self.dwell.setObjectName("dwell")
        self.label_4 = QtWidgets.QLabel(self.scan)
        self.label_4.setGeometry(QtCore.QRect(530, 100, 81, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setTextFormat(QtCore.Qt.AutoText)
        self.label_4.setScaledContents(False)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label = QtWidgets.QLabel(self.scan)
        self.label.setGeometry(QtCore.QRect(140, 70, 40, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_12 = QtWidgets.QLabel(self.scan)
        self.label_12.setGeometry(QtCore.QRect(240, 70, 51, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setObjectName("label_12")
        self.label_16 = QtWidgets.QLabel(self.scan)
        self.label_16.setGeometry(QtCore.QRect(350, 70, 51, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setObjectName("label_16")
        self.label_3 = QtWidgets.QLabel(self.scan)
        self.label_3.setGeometry(QtCore.QRect(450, 70, 51, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setTextFormat(QtCore.Qt.AutoText)
        self.label_3.setScaledContents(False)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_7 = QtWidgets.QLabel(self.scan)
        self.label_7.setGeometry(QtCore.QRect(640, 70, 131, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_6 = QtWidgets.QLabel(self.scan)
        self.label_6.setGeometry(QtCore.QRect(30, 90, 71, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.radioButton_1d = QtWidgets.QRadioButton(self.scan)
        self.radioButton_1d.setGeometry(QtCore.QRect(40, 20, 95, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_1d.sizePolicy().hasHeightForWidth())
        self.radioButton_1d.setSizePolicy(sizePolicy)
        self.radioButton_1d.setStyleSheet("font: 75 12pt \"Arial\";")
        self.radioButton_1d.setObjectName("radioButton_1d")
        self.radioButton_2d = QtWidgets.QRadioButton(self.scan)
        self.radioButton_2d.setGeometry(QtCore.QRect(140, 20, 95, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_2d.sizePolicy().hasHeightForWidth())
        self.radioButton_2d.setSizePolicy(sizePolicy)
        self.radioButton_2d.setStyleSheet("font: 75 12pt \"Arial\";\n"
"border-color: rgb(255, 235, 119);\n"
"")
        self.radioButton_2d.setChecked(True)
        self.radioButton_2d.setObjectName("radioButton_2d")
        self.groupBox_2 = QtWidgets.QGroupBox(self.scan)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 220, 991, 241))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox_2.setStyleSheet("font: 10pt \"Arial\";")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.checkBox = QtWidgets.QCheckBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox.sizePolicy().hasHeightForWidth())
        self.checkBox.setSizePolicy(sizePolicy)
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout_2.addWidget(self.checkBox, 0, 4, 1, 1)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_6.sizePolicy().hasHeightForWidth())
        self.lineEdit_6.setSizePolicy(sizePolicy)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout_2.addWidget(self.lineEdit_6, 0, 3, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout_2.addWidget(self.comboBox, 0, 0, 1, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_5.sizePolicy().hasHeightForWidth())
        self.lineEdit_5.setSizePolicy(sizePolicy)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout_2.addWidget(self.lineEdit_5, 0, 2, 1, 1)
        self.HXN_GUI_tabs.addTab(self.scan, "")
        self.diff = QtWidgets.QWidget()
        self.diff.setObjectName("diff")
        self.HXN_GUI_tabs.addTab(self.diff, "")
        self.xanes = QtWidgets.QWidget()
        self.xanes.setObjectName("xanes")
        self.HXN_GUI_tabs.addTab(self.xanes, "")
        self.tomo = QtWidgets.QWidget()
        self.tomo.setObjectName("tomo")
        self.HXN_GUI_tabs.addTab(self.tomo, "")
        self.alignement = QtWidgets.QWidget()
        self.alignement.setObjectName("alignement")
        self.HXN_GUI_tabs.addTab(self.alignement, "")
        self.gridLayout.addWidget(self.HXN_GUI_tabs, 0, 0, 1, 1)
        window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1074, 26))
        self.menubar.setObjectName("menubar")
        window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(window)
        self.statusbar.setObjectName("statusbar")
        window.setStatusBar(self.statusbar)

        self.retranslateUi(window)
        self.HXN_GUI_tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(window)

    def retranslateUi(self, window):
        _translate = QtCore.QCoreApplication.translate
        window.setWindowTitle(_translate("window", "MainWindow"))
        self.Select_Motor_4.setItemText(0, _translate("window", "zpssx"))
        self.Select_Motor_4.setItemText(1, _translate("window", "zpssy"))
        self.Select_Motor_4.setItemText(2, _translate("window", "zpssz"))
        self.x_start.setSuffix(_translate("window", "um"))
        self.y_start.setSuffix(_translate("window", "um"))
        self.Select_Motor_3.setItemText(0, _translate("window", "zpssy"))
        self.Select_Motor_3.setItemText(1, _translate("window", "zpssx"))
        self.Select_Motor_3.setItemText(2, _translate("window", "zpssz"))
        self.Dets_2.setItemText(0, _translate("window", "dets1"))
        self.Dets_2.setItemText(1, _translate("window", "dets2"))
        self.Dets_2.setItemText(2, _translate("window", "dets3"))
        self.label_8.setText(_translate("window", "Total Aq.Time (min)"))
        self.tot_time.setText(_translate("window", "1"))
        self.res.setText(_translate("window", "1000"))
        self.strat.setText(_translate("window", "Start"))
        self.label_4.setText(_translate("window", "Dwell Time"))
        self.label.setText(_translate("window", "Motors"))
        self.label_12.setText(_translate("window", "Start"))
        self.label_16.setText(_translate("window", "End"))
        self.label_3.setText(_translate("window", "Steps"))
        self.label_7.setText(_translate("window", "Resolution (nm)"))
        self.label_6.setText(_translate("window", "Detectors"))
        self.radioButton_1d.setText(_translate("window", "Fly1D"))
        self.radioButton_2d.setText(_translate("window", "Fly2D"))
        self.checkBox.setText(_translate("window", "Normlization"))
        self.lineEdit_6.setText(_translate("window", "Element"))
        self.comboBox.setItemText(0, _translate("window", "Plot"))
        self.comboBox.setItemText(1, _translate("window", "erf_fit"))
        self.comboBox.setItemText(2, _translate("window", "return_line_center"))
        self.lineEdit_5.setText(_translate("window", "Scan ID"))
        self.HXN_GUI_tabs.setTabText(self.HXN_GUI_tabs.indexOf(self.scan), _translate("window", "Image Scan"))
        self.HXN_GUI_tabs.setTabText(self.HXN_GUI_tabs.indexOf(self.diff), _translate("window", "Diffraction"))
        self.HXN_GUI_tabs.setTabText(self.HXN_GUI_tabs.indexOf(self.xanes), _translate("window", "XANES"))
        self.HXN_GUI_tabs.setTabText(self.HXN_GUI_tabs.indexOf(self.tomo), _translate("window", "Tomography"))
        self.HXN_GUI_tabs.setTabText(self.HXN_GUI_tabs.indexOf(self.alignement), _translate("window", "Alignment (experts only)"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    window = QtWidgets.QMainWindow()
    ui = Ui_window()
    ui.setupUi(window)
    window.show()
    sys.exit(app.exec_())
